### PR TITLE
adds a in_place configuration to rollup that removes raw datapoints.

### PR DESCRIPTION
**Pull request by chpache**

### CODE REVIEW

**Comment by chpache** [comment]
would this make sense? if so, I may add some test for it.
basically, my use case is to rollup a metric and save to the same, to create averaged datapoints. I'm quite happy having just one metrics with raw/life datapoints for the latest one and aggregated datapoints for the rest.

**Comment by brianhks** [comment]
The concern I have is that the raw data for each rollup query is not entirely used for the rollup.  Lets say I get two data points an hour and I want to create a 1 hour rollup (not practical but proves the point)

Here is the time for each data point, assuming the data value is 1
[1:20, 1:50, 2:20, 2:50, 3:20, 3:50, 4:20]

If I rolled up the data for each hour I would get 
[1:00=2, 2:00=2, 3:00=2, 4:00=1]

When we do the rollup we trim off the last data point as it is usually only a partial value (in this case 1).  The next rollup we do we overlap with the previous query so we get full values for each time period.

The problem I see with your change is that the first rollup query runs and the 4:20 data point gets deleted and subsequently won't show up in the next rollup query.

The directly I would like to head for solving this problem is to always write rollup data to a different metric name.  I'm planning on adding a feature that lets you query both the rollup and the live data at the same time and the backend merges the data together into one result.  This gives you the same effect without losing data.  Then you can set some other policy on when to delete old data.

**Comment by chpache** [comment]
Thanks, well, I get your point. I kind of understand why you "trim" the last datapoint, as you assume the new datapoints are representative for the full hours. I was really measure focused, assuming the new datapoints are average for a time range which is always the same (1h full in your example). (BTW, I also set a end_relative and ensure the rollup range are always the same.)

The issue I have with your solution is that this will be done on query and that if I want to keep one year old metrics, I keep the same number of points that the current one. Is this correct?

**Comment by brianhks** [comment]
I'm not quite sure I understand what your question is so, here is my best answer that may not be what you are looking for.

My thought is that you have raw data that you ttl for say 7 days.  From that data you have a rollup job that aggregates by an hour and in turn ttls the data for 1 year.  Then when you make queries to the raw data you would specify the rollup metric to use.  Lets say you run the rollup every day and you want to query for the last month of data.  Kairos would first query the rollup and then patch in the last day of data from the raw.  (this is how it works in my head anyway)

Brian

**Comment by chpache** [comment]
yeah, that seams perfectly fine. 
Then, I think this PR has no reason and will close it. Really looking forward for your solution!
Thanks

**Pull request closed without merging**
