### PR TITLE
Merged auth pull request #531

### PR DESCRIPTION
**Pull request by brianhks**
This is a clean merge from #531 into develop

### CODE REVIEW

**Comment by brianhks** [comment]
I need to add a unit test and clean up the docs in the config file, they aren't quite accurate.

**Comment by kyleboyle** [comment]
Supporting JAAS is the first step as defined here, but I think we should also add configurable constraint configuration to kairosdb.conf to support role based authorization. It could be a map of pathSpec strings to a http method and list of roles which could be used to generate Constraints inside WebServer.java:initializeAuth(). The default "allow all" would be the base constraint over which additional role restrictions would be laid.

The basic use case I can think of is to define read only users (execute queries and read meta data), and write users (ingest and administration). One wrinkle though is how to prevent a save_as query from being executed by a user who should only have read permission.

One solution to the above is to have a reserved pathSpec config item called something like "_save_as" which maps to a list of roles that are allowed to use the save_as aggregator. The MetricsResource could then enforce the current user belonging to one of those roles if the query contains the save as aggregator.

Example pathSpec, Method, Role tuples:
```
"/api/v1/datapoints/metric/*", ["DELETE", "POST"], ["admin"]
"/api/v1/datapoints/delete/*", ["*"], ["admin"]
"/api/v1/datapoints/query/*", ["*"], ["**"]
"/api/v1/datapoints/*", ["POST"], ["ingest"]
"/api/v1/rollups/*", ["*"], ["admin"]
```

Question: Can this be applied to telnet and graphite protocols?

**Comment by brianhks** [comment]
I like the idea but I think I'll leave it for a another release.  I'll make sure and keep track of this discussion in another ticket or at least reference this one.

**Comment by kyleboyle** [comment]
Ok. Could you explain the reason for your decision to make future collaboration easier.

**Comment by brianhks** [comment]
I'm trying to shorten my list of new features so I can get this release out.  It has been sitting around for a long time so I'm trying to focus on critical/easy items that are left.

**Pull request merged**
