### PR TITLE
Makes rollup sample periods deterministic

### PR DESCRIPTION
**Pull request by kyleboyle**
If the rollup sample size is multiple units, align the first sample start time
on the boundary of the next highest granularity. Eg a 10 min sample size should
start on minute zero of hour (or minute 10, or minute 20, etc). Eg a quarterly rollup (3 MONTHS) should start on the first of January, or the first of April, etc. This alignment step is aborted if the number of units is not a factor of the number of units in the next highest granularity. EG a 13 minute rollup will not be aligned to the start of the hour because 13 is not a factor of 60 (60 mins in an hour).

Also the RollupProcessorImpl test is now deterministic and it won't fail
depending on the current clock minute, as the current clock minute was the
sample boundary.

Now multiple metrics using the same multi-unit sample size (even running on different cluster members) produce rollups on the same sample boundaries.

The Rollup job config has a time_zone property which, if specified, will be used in sample time alignment. EG if there is a 1 hour rollup and its time_zone is set to "America/St_Johns" (which is -3:30) then the sample periods will start/stop on the UTC 30 mins past the hour.

Here is an example of the sample logs for 2 rollup tasks which have the same config except for the timezone. You can see that the stj task is aligned on the bottom of the hour because the stj timezone is -3:30
```
17:59:38.172 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:66] - Executing Rollup Task: demo_data_stj for Rollup  demo_data_rollup
17:59:38.187 [QuartzScheduler_Worker-4] DEBUG [RollupProcessorImpl.java:59] - startTime = Wed Jan 01 17:57:38 EST 2020
17:59:38.196 [QuartzScheduler_Worker-4] DEBUG [RollupProcessorImpl.java:82] - Sampling period SamplingPeriod{startTime=Wed Jan 01 17:50:00 EST 2020, endTime=Wed Jan 01 18:10:00 EST 2020}
17:59:38.197 [QuartzScheduler_Worker-4] DEBUG [RollupProcessorImpl.java:123] - Execute Rollup: demo_data Start time: Wed Jan 01 17:50:00 EST 2020 End time: Wed Jan 01 18:10:00 EST 2020
17:59:38.247 [QuartzScheduler_Worker-4] DEBUG [RollupProcessorImpl.java:98] - Rollup Task: demo_data_stj for Rollup demo_data_stj data point count of 0
17:59:38.301 [QuartzScheduler_Worker-4] INFO  [RollUpJob.java:105] - Rollup Task: demo_data_stj for Rollup  demo_data_rollup completed

18:00:18.105 [QuartzScheduler_Worker-3] INFO  [RollUpJob.java:66] - Executing Rollup Task: demo_data_utc for Rollup  demo_data_rollup
18:00:18.122 [QuartzScheduler_Worker-3] DEBUG [RollupProcessorImpl.java:59] - startTime = Wed Jan 01 17:59:18 EST 2020
18:00:18.124 [QuartzScheduler_Worker-3] DEBUG [RollupProcessorImpl.java:82] - Sampling period SamplingPeriod{startTime=Wed Jan 01 17:40:00 EST 2020, endTime=Wed Jan 01 18:00:00 EST 2020}
18:00:18.124 [QuartzScheduler_Worker-3] DEBUG [RollupProcessorImpl.java:123] - Execute Rollup: demo_data Start time: Wed Jan 01 17:40:00 EST 2020 End time: Wed Jan 01 18:00:00 EST 2020
18:00:18.163 [QuartzScheduler_Worker-3] DEBUG [RollupProcessorImpl.java:98] - Rollup Task: demo_data_utc for Rollup demo_data_utc data point count of 0
18:00:18.214 [QuartzScheduler_Worker-3] INFO  [RollUpJob.java:105] - Rollup Task: demo_data_utc for Rollup  demo_data_rollup completed
```

Screen Shot 2020-01-01 at 6 06 38 PM

### CODE REVIEW

**Comment by kyleboyle** [comment]
I welcome comments on the implementation approach, this is my first server code change

**Comment by kyleboyle** [comment]
@brianhks I believe I have finished with this enhancement. My intention is to improve usability and predictability of the the rollup feature.

**Comment by brianhks** [comment]
We will take a look at this pull request.  Typically the align sampling will correct most of the problems you bring up, except the rollup code wasn't adhering to that.  Jeff just checked in a change a few days ago that addressed it.

**Comment by kyleboyle** [comment]
> We will take a look at this pull request. Typically the align sampling will correct most of the problems you bring up, except the rollup code wasn't adhering to that. Jeff just checked in a change a few days ago that addressed it.

The changes made by Jeff only address alignment of the intervals to the specified sample size in the UTC time zone. I believe the rest of the enhancements that I made are still needed when the sampling size is greater than 1 unit to get sane alignment, plus the timezone considerations.

**Comment by brianhks** [comment]
Yes I realize that,  Jeff is going to manually pull in your changes and merge with his.

**Comment by kyleboyle** [comment]
Awesome, thanks!

**Comment by kyleboyle** [comment]
I resolved the conflicts

**Comment by jsabin** [comment]
Thanks for your work on this pull request. You exposed a bug where I was not handling the value part of a Sampling. 

Your pull request is in two parts. The first is to adjust roll-ups based on the timezone. This is a good change that I had not considered. I will include it in the develop branch.

The second part is adjusting the start time based on the sampling value. Your solution adjusts to the closest value that is divisible by the next largest sampling unit. I don't think this is the correct solution since after multiple sampling periods the alignment will be off. Although I think you are on the right track and you definitely got Brian and I talking about this. We think a better solution is to successively take the next largest sampling until it is divisible or if not use the epoch (Jan 1, 1970).  

So I won't be accepting your pull request but will use the timezone changes and portions from the other changes.

Thanks again.

**Comment by kyleboyle** [comment]
Awesome. Happy to spark discussion. I would love to see the unit tests pass that I defined with your implementation - if so I'm happy and consider it a success.

**Comment by brianhks** [comment]
I made a change to the range aggregator so the methods that determine the start and end time of the range are publicly available.  I committed it last night to develop.  Jeff, lets look at using these and or modifying them to work for this.

**Comment by jsabin** [comment]
I incorrectly read your unit tests and misunderstood what you were doing. I now understand that what you were doing was correct as long as the sampling was divisible by the larger time unit. If not you just used the start time. Sorry for the confusion.

I have pulled in your timezone changes. I did not take your time adjustment code because we decided it would be best to use the same code that the aggregators are using to do the time adjustments. It's slightly different than what you were doing but pretty close. 

Thanks again for your contribution and for catching the problem.

**Pull request closed without merging**
