### PR TITLE
Feature/new auth

### PR DESCRIPTION
**Pull request by ehatch90**
This brings in Jetty JAAS and LDAP auth functionality. This reworks the basic auth provided in KairosDB as well. There are two other modules that JAAS includes which are the DataSourceLoginModule and JDBCLoginModule. Base conf files are not included for these other two but you can probably find samples for them.

JAAS allows you to enable multiple auth types together as well and they can be used in different logical configurations (and/or). Details and links for all of this can be found in the kairosdb.conf file comments.

### CODE REVIEW

**Comment by brianhks** [comment]
Wow something went wrong with this pull request.  It has a gadgillion changes.

**Comment by kyleboyle** [comment]
@brianhks Is there an interest in expanding this change to support configurable roles for Resources/Endpoints. Supporting JAAS is the first step as defined here, but we would also need to add constraint configuration to kairosdb.conf. It could be a map of pathSpec strings to a list of roles which could be used to generate Constraints. 

The basic use case I can think of is to define read only users (execute queries and read meta data), and write users (ingest and administration). One wrinkle though is how to prevent a save_as query from being executed by a user who should only have read permission.

**Comment by brianhks** [comment]
@kyleboyle Yes I think there is.  That is effectively what we are trying to do at Proofpoint.  In our case we have separated Kairos read and write instances and people who query can only access the read instances.  Yes save_as is a tricky back door and if I fix it, it will lock me out of using it at work ;)

I'll understand your suggestion more after I unwind this crazy pull request.

**Comment by kyleboyle** [comment]
I just looked at the "Files Changed" section to see the diff, this can't be merged as-is.

One solution to the save_as wrinkle is to have a reserved pathSpec item called something like "_save_as" which maps to a list of roles that are allowed to use the save_as aggregator. The MetricsResource could then enforce the current user belonging to one of those roles if the query contains the save as aggregator.

**Comment by brianhks** [comment]
There is a long story behind the files changed.  Anyway I'm going to create a new branch from the changes which are quite small and then we can discuss additional changes from there.

**Comment by brianhks** [comment]
Let's discuss further changes on #600

**Pull request closed without merging**
